periodics:
- agent: kubernetes
  cluster: build01
  cron: 0 0 * * *
  decorate: true
  extra_refs:
  - base_ref: master
    org: app-sre
    repo: deployment-validation-operator
  labels:
    ci-operator.openshift.io/cloud: aws
    ci-operator.openshift.io/cloud-cluster-profile: aws-observability
    ci.openshift.io/generator: prowgen
    pj-rehearse.openshift.io/can-be-rehearsed: "true"
  name: periodic-ci-app-sre-deployment-validation-operator-master-dvo-e2e-tests-periodic
  spec:
    containers:
    - args:
      - --gcs-upload-secret=/secrets/gcs/service-account.json
      - --image-import-pull-secret=/etc/pull-secret/.dockerconfigjson
      - --lease-server-credentials-file=/etc/boskos/credentials
      - --report-credentials-file=/etc/report/credentials
      - --secret-dir=/secrets/ci-pull-credentials
      - --secret-dir=/usr/local/dvo-e2e-tests-periodic-cluster-profile
      - --target=dvo-e2e-tests-periodic
      command:
      - ci-operator
      image: ci-operator:latest
      imagePullPolicy: Always
      name: ""
      resources:
        requests:
          cpu: 10m
      volumeMounts:
      - mountPath: /etc/boskos
        name: boskos
        readOnly: true
      - mountPath: /secrets/ci-pull-credentials
        name: ci-pull-credentials
        readOnly: true
      - mountPath: /usr/local/dvo-e2e-tests-periodic-cluster-profile
        name: cluster-profile
      - mountPath: /secrets/gcs
        name: gcs-credentials
        readOnly: true
      - mountPath: /secrets/manifest-tool
        name: manifest-tool-local-pusher
        readOnly: true
      - mountPath: /etc/pull-secret
        name: pull-secret
        readOnly: true
      - mountPath: /etc/report
        name: result-aggregator
        readOnly: true
    serviceAccountName: ci-operator
    volumes:
    - name: boskos
      secret:
        items:
        - key: credentials
          path: credentials
        secretName: boskos-credentials
    - name: ci-pull-credentials
      secret:
        secretName: ci-pull-credentials
    - name: cluster-profile
      secret:
        secretName: cluster-secrets-aws-observability
    - name: manifest-tool-local-pusher
      secret:
        secretName: manifest-tool-local-pusher
    - name: pull-secret
      secret:
        secretName: registry-pull-credentials
    - name: result-aggregator
      secret:
        secretName: result-aggregator
