base_images:
  operator-sdk:
    name: "4.12"
    namespace: origin
    tag: operator-sdk
build_root:
  from_repository: true
images:
- dockerfile_path: build/Dockerfile
  to: dvo-operator
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: coverage
  commands: |
    export CODECOV_TOKEN=$(cat /tmp/secret/CODECOV_TOKEN)
    make coverage
  container:
    from: src
  secret:
    mount_path: /tmp/secret
    name: deployment-validation-operator-codecov-token
- as: publish-coverage
  commands: |
    export CODECOV_TOKEN=$(cat /tmp/secret/CODECOV_TOKEN)
    make coverage
  container:
    from: src
  postsubmit: true
  secret:
    mount_path: /tmp/secret
    name: deployment-validation-operator-codecov-token
- as: lint
  commands: make lint
  container:
    from: src
- as: test
  commands: make test
  container:
    from: src
- as: validate
  commands: make validate
  container:
    from: src
- as: deployment-validation-operator-e2e-tests
  cluster_claim:
    architecture: amd64
    cloud: aws
    owner: openshift-ci
    product: ocp
    timeout: 1h0m0s
    version: "4.12"
  steps:
    test:
    - as: install
      cli: latest
      commands: |
        python hack/generate-operator-bundle-contents.py -n deployment-validation-operator -c testing -i ${DVO_OPERATOR} -t latest -o bundle/manifests/ --no-nodeAffinity
        oc create namespace deployment-validation-operator
        operator-sdk generate bundle --package=deployment-validation-operator --input-dir=bundle/manifests --metadata
        podman build -f bundle.Dockerfile -t quay.io/jfula/dvo-bundle-test
        podman push quay.io/jfula/dvo-bundle-test
        operator-sdk run bundle quay.io/jfula/dvo-bundle-test:latest --namespace deployment-validation-operator --skip-tls
        oc wait --for condition=Available -n deployment-validation-operator deployment-operator
      dependencies:
      - env: DVO_OPERATOR
        name: dvo-operator
      from: operator-sdk
      resources:
        requests:
          cpu: 100m
zz_generated_metadata:
  branch: master
  org: app-sre
  repo: deployment-validation-operator
